## Consumer Sentiment vs Consumer Consumption

### Preparation
---

#### Import statements

In [246]:
import pandas as pd

#### Load the Datasets

In [247]:
consumer_sentiment_df = pd.read_csv("./Datasets/UMCSENT.csv")
consumer_economic_conditions_df= pd.read_excel("./Datasets/Current_Economic_Conditions.xlsx")
consumer_expectations_df= pd.read_excel("./Datasets/Consumer_Expectations.xlsx")

Use of the data is from 2000 onwards - so go to excel and remove the earlier values for ease.

### Initial checks
---

<section class="data-checks">

  <h5>First Set of Checks</h5>
  <ul>
    <li>Head</li>
    <li>Tail</li>
    <li>Datatypes</li>
    <li>Columns</li>
    <li>Shape</li>
  </ul>

  <h5>Second Set of Checks</h5>
  <ul>
    <li>Remove unused columns</li>
    <li>Check duplicate values</li>
    <li>Missing values</li>
  </ul>
</section>

#### Consumer sentiment checks

In [248]:
#### first set of checks
consumer_sentiment_df.sample(5)         # Date is not the index - np
consumer_sentiment_df.head()            # Starts at the correct date
consumer_sentiment_df.tail()            # ends at 2026-01
consumer_sentiment_df.columns           # No spaces which is good but do need to rename  + No need to drop columns
consumer_sentiment_df.dtypes            # Observation date needs to be converted

    #### Initial adjustments
consumer_sentiment_df.rename(columns={"observation_date":"Date","UMCSENT":"Sentiment_index"}, inplace=True)     # Fixed the index
consumer_sentiment_df["Date"]= pd.to_datetime(consumer_sentiment_df["Date"], format ="%d/%m/%Y")               # Datetime conversion but it is alsop in daily format so convert to thrifst of the mont



#### Second set of checks
consumer_sentiment_df.columns           #No need to drop columns
consumer_sentiment_df.duplicated(subset="Date", keep=False).value_counts()      # All are false so no duplicated values
consumer_sentiment_df.isna().sum()                                              # No missing values for any of the dates + Need to check if all the 12 months are there in the dataset

        # Checks to make sure that all the dates are there for the period from 2000 to 2026.
print(pd.date_range(start= "2000-01-01", end = "2026-01-01", freq="MS").difference(consumer_sentiment_df["Date"]))
                    # Sets up a date range, looks at the month start, then compares and then prints the ones that are different
                    ## There are no missing values

consumer_sentiment_df

DatetimeIndex([], dtype='datetime64[us]', freq='MS')

          Date  Sentiment_index
0   2000-01-01            112.0
1   2000-02-01            111.3
2   2000-03-01            107.1
3   2000-04-01            109.2
4   2000-05-01            110.7
..         ...              ...
308 2025-09-01             55.1
309 2025-10-01             53.6
310 2025-11-01             51.0
311 2025-12-01             52.9
312 2026-01-01             56.4

[313 rows x 2 columns]

#### Consumer Expectations checks

In [249]:
#### first set of checks
consumer_expectations_df.sample(5)
consumer_expectations_df.head(30)       # Starts at the correct date
consumer_expectations_df.tail()         # ends at 2026-01
consumer_expectations_df.dtypes          # Observation no need to be converted since its a datetime.
consumer_expectations_df.columns        # No spaces which is good but do need to rename  + No need to drop columns

    #### Initial adjustments
consumer_expectations_df.rename(columns={"Datemy":"Date","ICE":"Consumer_Expectations_index"}, inplace=True)     # Fixed the index

#### Second set of checks
consumer_sentiment_df.columns           #Need to remove the recessions column

consumer_sentiment_df.duplicated(subset="Date", keep=False).value_counts()      # All are false so no duplicated values
consumer_sentiment_df.isna().sum()                                              # No missing values for any of the dates + Need to check if all the 12 months are there in the dataset

        # Checks to make sure that all the dates are there for the period from 2000 to 2026.
print(pd.date_range(start= "2000-01-01", end = "2026-01-01", freq="MS").difference(consumer_expectations_df["Date"]))
                    # Sets up a date range, looks at the month start, then compares and then prints the ones that are different
                    # There are no missing values( from geeks for geeeks)

    #### Adjustments
consumer_expectations_df.drop(columns=["RECESSION"], inplace=True)          ## Remove the recession column
consumer_expectations_df["Date"]= pd.to_datetime(consumer_expectations_df["Date"])
consumer_expectations_df

DatetimeIndex([], dtype='datetime64[us]', freq='MS')

          Date  Consumer_Expectations_index
0   2000-01-01                        103.6
1   2000-02-01                        105.8
2   2000-03-01                        106.0
3   2000-04-01                        104.4
4   2000-05-01                        103.4
..         ...                          ...
309 2025-10-01                         52.6
310 2025-11-01                         51.0
311 2025-12-01                         52.0
312 2026-01-01                         54.2
313 2026-02-01                         56.1

[314 rows x 2 columns]

#### Consumer Economic Conditions checks

In [250]:
#### first set of checks
consumer_economic_conditions_df.sample(5)         # Date is not the index - np
consumer_economic_conditions_df.head()            # Starts at the correct date
consumer_economic_conditions_df.tail()            # ends at 2026-02
consumer_economic_conditions_df.columns           # No spaces which is good but do need to rename  + No need to drop columns
consumer_economic_conditions_df.dtypes            # Npo changes needed

    #### Initial adjustments
consumer_economic_conditions_df.rename(columns={"Unnamed: 0":"Date","3mma":"Economic_Conditions_index"}, inplace=True)     # Fixed the index


#### Second set of checks
consumer_economic_conditions_df.columns           #Need to drop the recessions column
consumer_economic_conditions_df.duplicated(subset="Date", keep=False).value_counts()      # All are false so no duplicated values
consumer_economic_conditions_df.isna().sum()                                              # No missing values for any of the dates+ missing for recession + Need to check if all the 12 months are there

    # Adjustments
consumer_economic_conditions_df.drop(columns=["Recession"], inplace=True)       # Remove the Recession column
consumer_economic_conditions_df["Date"]= pd.to_datetime(consumer_economic_conditions_df["Date"])



        # Checks to make sure that all the dates are there for the period from 2000 to 2026.
print(pd.date_range(start= "2000-01-01", end = "2026-01-01", freq="MS").difference(consumer_economic_conditions_df["Date"]))
                    # Sets up a date range, looks at the month start, then compares and then prints the ones that are different
                    ## There are no missing values
consumer_economic_conditions_df

DatetimeIndex([], dtype='datetime64[us]', freq='MS')

          Date  Economic_Conditions_index
0   2000-01-01                      115.4
1   2000-02-01                      115.4
2   2000-03-01                      116.5
3   2000-04-01                      116.7
4   2000-05-01                      117.7
..         ...                        ...
309 2025-10-01                       60.2
310 2025-11-01                       56.7
311 2025-12-01                       53.4
312 2026-01-01                       52.3
313 2026-02-01                       54.1

[314 rows x 2 columns]

### Merge all (Sentiment) Indicators
---

In [251]:
initial_df = pd.merge(consumer_economic_conditions_df, consumer_expectations_df, on="Date", how="inner")
clean_df= pd.merge(initial_df,consumer_sentiment_df, on="Date", how="outer")
clean_df.head(20)

,Date,Economic_Conditions_index,Consumer_Expectations_index,Sentiment_index
0,2000-01-01,115.4,103.6,112.0
1,2000-02-01,115.4,105.8,111.3
2,2000-03-01,116.5,106.0,107.1
3,2000-04-01,116.7,104.4,109.2
4,2000-05-01,117.7,103.4,110.7
5,2000-06-01,117.6,103.1,106.4
6,2000-07-01,116.4,103.4,108.3
7,2000-08-01,113.9,103.1,107.3
8,2000-09-01,112.9,104.0,106.8
9,2000-10-01,112.7,102.7,105.8
10,2000-11-01,114.2,101.9,107.6
11,2000-12-01,113.7,97.7,98.4
12,2001-01-01,111.7,92.9,94.7
13,2001-02-01,108.0,86.0,90.6
14,2001-03-01,105.6,83.7,91.5
15,2001-04-01,102.4,82.3,88.4
16,2001-05-01,101.2,83.8,92.0
17,2001-06-01,100.6,84.8,92.6
18,2001-07-01,100.8,86.9,92.4
19,2001-08-01,100.5,86.8,91.5